# Problem 1

In [1]:
import numpy as np

arr = np.random.randint(1, 51, size=(5, 4))
print(arr)

[[45 32  3  4]
 [ 7 45 34 32]
 [36 42 45  3]
 [43 36 36 44]
 [27 29 35 41]]


In [2]:
for i in range(3, -1, -1):
    print(arr[3 - i][i])

4
34
42
43


In [3]:
mean_val = arr.mean()
new_arr = arr[arr >= mean_val]
print(new_arr)

[45 32 45 34 32 36 42 45 43 36 36 44 35 41]


In [4]:
def numpy_boundary_traversal(mat):
    if mat.size == 0:
        return []

    rows, cols = mat.shape
    result = []

    for j in range(cols):
        result.append(mat[0][j])

    for i in range(1, rows):
        result.append(mat[i][cols - 1])

    if rows > 1:
        for j in range(cols - 2, -1, -1):
            result.append(mat[rows - 1][j])

    if cols > 1:
        for i in range(rows - 2, 0, -1):
            result.append(mat[i][0])

    return result

print(numpy_boundary_traversal(arr))

[45, 32, 3, 4, 32, 3, 44, 41, 35, 29, 27, 43, 36, 7]


# Problem 2

In [5]:
rand_arr = np.random.uniform(0, 10, 20)
print(rand_arr)

[4.32351092 1.37546935 1.80994969 1.27791775 1.20271125 0.35056545
 1.66604072 6.33029099 3.15400957 2.55104931 4.2906476  1.92641237
 1.40985377 4.16960107 7.12246316 6.34002034 5.06651768 4.96729088
 9.49911912 0.05985162]


In [6]:
print(np.round(rand_arr, 2))

[4.32 1.38 1.81 1.28 1.2  0.35 1.67 6.33 3.15 2.55 4.29 1.93 1.41 4.17
 7.12 6.34 5.07 4.97 9.5  0.06]


In [13]:
rand_arr = np.where(rand_arr < 5, rand_arr ** 2, rand_arr)
print(rand_arr)

[1.86927467e+01 1.89191594e+00 3.27591789e+00 1.63307377e+00
 1.44651435e+00 1.22896137e-01 2.77569167e+00 6.33029099e+00
 9.94777635e+00 6.50785258e+00 1.84096568e+01 3.71106460e+00
 1.98768766e+00 1.73855731e+01 7.12246316e+00 6.34002034e+00
 5.06651768e+00 2.46739787e+01 9.49911912e+00 3.58221635e-03]


In [15]:
def numpy_alternate_sort(array):
    sorted_arr = np.sort(array)
    result = []
    left, right = 0, len(sorted_arr) - 1
    while left <= right:
        result.append(sorted_arr[left])
        left += 1
        if left <= right:
            result.append(sorted_arr[right])
            right -= 1
    return np.array(result)

print(numpy_alternate_sort(rand_arr))

[3.58221635e-03 2.46739787e+01 1.22896137e-01 1.86927467e+01
 1.44651435e+00 1.84096568e+01 1.63307377e+00 1.73855731e+01
 1.89191594e+00 9.94777635e+00 1.98768766e+00 9.49911912e+00
 2.77569167e+00 7.12246316e+00 3.27591789e+00 6.50785258e+00
 3.71106460e+00 6.34002034e+00 5.06651768e+00 6.33029099e+00]


# Problem 3

In [19]:
import pandas as pd
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'
    
data = {
    'Name': [f'{np.random.choice(["Smith", "Johnson", "Williams", "Jones", "Brown"])}' for _ in range(10)],
    'Subject': [f'{np.random.choice(["Math", "Physics", "English", "Chemistry"])}' for i in range(10)],
    'Score': np.random.randint(50, 101, size=10),
    'Grade': [''] * 10
}
df = pd.DataFrame(data)
df['Grade'] = df['Score'].apply(assign_grade)
print(df)

       Name    Subject  Score Grade
0     Brown    Physics     61     D
1     Jones    Physics     56     F
2   Johnson    Physics     97     A
3     Jones    English     63     D
4     Smith       Math     82     B
5   Johnson    Physics     87     B
6  Williams  Chemistry     77     C
7     Smith  Chemistry     65     D
8     Smith    Physics     80     B
9   Johnson       Math     54     F


In [20]:
print(df.sort_values(by='Score', ascending=False))

       Name    Subject  Score Grade
2   Johnson    Physics     97     A
5   Johnson    Physics     87     B
4     Smith       Math     82     B
8     Smith    Physics     80     B
6  Williams  Chemistry     77     C
7     Smith  Chemistry     65     D
3     Jones    English     63     D
0     Brown    Physics     61     D
1     Jones    Physics     56     F
9   Johnson       Math     54     F


In [22]:
print(df.groupby('Subject')['Score'].mean())

Subject
Chemistry    71.0
English      63.0
Math         68.0
Physics      76.2
Name: Score, dtype: float64


In [23]:
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print(pandas_filter_pass(df))

      Name  Subject  Score Grade
2  Johnson  Physics     97     A
4    Smith     Math     82     B
5  Johnson  Physics     87     B
8    Smith  Physics     80     B


# Problem 4

In [24]:
import random
import pandas as pd

positive_reviews = [
    "Absolutely loved it!", "A masterpiece.", "Brilliant acting and story.", "Highly recommended.", "A must-watch.",
    "Fantastic from start to finish.", "Heartwarming and inspiring.", "Exceeded my expectations.", "A delightful experience.", "Superb direction.",
    "The cast was phenomenal.", "A cinematic triumph.", "Beautifully shot.", "An emotional rollercoaster.", "A true classic.",
    "Loved every minute.", "A feel-good movie.", "The best film I've seen this year.", "Incredible visuals.", "A joy to watch.",
    "Perfectly executed.", "A wonderful journey.", "A breath of fresh air.", "A powerful message.", "Unforgettable.",
    "Stellar performances.", "A visual treat.", "A moving story.", "Simply amazing.", "A work of art.",
    "Captivating and engaging.", "A thoroughly enjoyable film.", "A top-notch production.", "A charming film.", "A real gem.",
    "A fantastic ride.", "A brilliant script.", "A heartwarming tale.", "A beautiful narrative.", "A stunning achievement.",
    "A delightful surprise.", "A well-crafted movie.", "A memorable experience.", "A must-see.", "A perfect blend of humor and drama.",
    "A touching story.", "A wonderful cast.", "A great watch.", "A feel-good experience.", "A top-tier film.", "A masterpiece of cinema."
]

negative_reviews = [
    "Terrible movie.", "A complete waste of time.", "Poor acting.", "Boring and predictable.", "Not worth watching.",
    "Disappointing from start to finish.", "Lacked depth.", "Uninspired and dull.", "Failed to impress.", "A forgettable experience.",
    "The plot was weak.", "Bad direction.", "Unconvincing performances.", "A mess of a film.", "Painfully slow.",
    "Overhyped and underwhelming.", "A tedious watch.", "Nothing special.", "A letdown.", "Unoriginal and bland.",
    "The script was awful.", "A boring storyline.", "A poor attempt.", "A waste of money.", "Not engaging.",
    "Mediocre at best.", "A total flop.", "Uninteresting characters.", "A disappointing movie.", "A lackluster film.",
    "A forgettable plot.", "A dull experience.", "A poorly made film.", "A snooze fest.", "A disaster.",
    "A weak narrative.", "A pointless movie.", "A bad experience.", "A failed attempt.", "A subpar film.",
    "A boring movie.", "A terrible script.", "A waste of time.", "A bland film.", "A disappointing story.",
    "A forgettable cast.", "A poorly executed film.", "A lack of originality.", "A dreadful movie.", "A bad watch.", "A mess."
]

# Shuffle to avoid order bias
random.seed(42)
all_reviews = [(review, "positive") for review in positive_reviews] + [(review, "negative") for review in negative_reviews]
random.shuffle(all_reviews)

# Create DataFrame
movie_reviews_df = pd.DataFrame(all_reviews, columns=["Review", "Sentiment"])
print(movie_reviews_df.head())

                      Review Sentiment
0      A well-crafted movie.  positive
1  Uninteresting characters.  negative
2         A dull experience.  negative
3          Superb direction.  positive
4           A tedious watch.  negative


In [25]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(movie_reviews_df['Review'])

print(X.shape)
print(vectorizer.get_feature_names_out()[:10])  # Show first 10 feature names

(102, 138)
['absolutely' 'achievement' 'acting' 'air' 'amazing' 'art' 'attempt'
 'awful' 'bad' 'beautiful']


In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, movie_reviews_df['Sentiment'], test_size=0.2, random_state=42)

In [29]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)
accuracy = classifier.score(X_test, y_test)
print(f"Accuracy of the Naive Bayes classifier: {accuracy:.2f}")

Accuracy of the Naive Bayes classifier: 0.67


In [30]:
def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)
    return prediction[0]

example_review = "This movie was absolutely fantastic!"
predicted_sentiment = predict_review_sentiment(classifier, vectorizer, example_review)
print(f"The predicted sentiment for the review '{example_review}' is: {predicted_sentiment}")


The predicted sentiment for the review 'This movie was absolutely fantastic!' is: positive


# Problem 5

In [ ]:
 

import pandas as pd
import numpy as np
np.random.seed(42)
data = {
    'text': [
        "Great product, very satisfied!", "Terrible quality, not worth the price.",
        "Excellent service and fast delivery.", "Very disappointed with the purchase.",
        "Highly recommend this item!", "Would not buy again, poor performance.",
        "Amazing quality, exceeded my expectations.", "Not as described, very unhappy.",
        "Fantastic experience, will shop again.", "Awful customer support, never again."
    ] * 10,
    'label': ['good', 'bad'] * 50
}   
df = pd.DataFrame(data)
print(df.head())


                                     text label
0          Great product, very satisfied!  good
1  Terrible quality, not worth the price.   bad
2    Excellent service and fast delivery.  good
3    Very disappointed with the purchase.   bad
4             Highly recommend this item!  good


In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=300, lowercase=True, stop_words='english')
X = vectorizer.fit_transform(df['text'])

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['label'])


In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [37]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import precision_recall_fscore_support
y_pred = model.predict(X_test)
precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average='binary')
print(f"Precision: {precision:.2f}, Recall: {recall:.2f}, F1-Score: {f1:.2f}")


Precision: 1.00, Recall: 1.00, F1-Score: 1.00


In [38]:
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)


sample_texts = [
    "This product is amazing!", 
    "I had a terrible experience with the service.", 
    "Highly recommend this to everyone!"
]
vectorized_texts = text_preprocess_vectorize(sample_texts, vectorizer)
print(vectorized_texts.toarray())


[[0.70710678 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.70710678 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.57735027 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.57735027 0.         0.         0.57735027 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.70710678 0.         0.         0.
  0.         0.         0.         0.         0.70710678 0.
  0.         0.         0.         0.         0.         0.        ]]
